<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>GCLog4j</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#debug</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#info</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#error</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#warn</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>common</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#timestamp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#threads</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sql</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#processresource</string>
				</dict>
			</array>
		</dict>
		<key>debug</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^DEBUG</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>entity.ignore.log4j</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#common</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>equal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keywords.equal</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.thread4.log4j</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\b\w+)(\=)(\w+\b)</string>
					<key>name</key>
					<string>entity.fatal.log4j</string>
				</dict>
			</array>
		</dict>
		<key>error</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^ERROR</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>entity.error.log4j</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#common</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>info</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^INFO</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>entity.ignore.log4j</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#common</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>processresource</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>ProcessResource\[</string>
					<key>end</key>
					<string>(\]\n)|(\n)</string>
					<key>name</key>
					<string>entity.thread4.log4j</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#equal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>sql</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=Creating.PreparedStatement.for)</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>entity.text.params.log4j</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(select(\s+distinct)?|insert\s+(ignore\s+)?into|update|delete|from|set|where|group\sby|or|like|and|union(\s+all)?|having|order\sby|limit|(inner|cross)\s+join|straight_join|(left|right)(\s+outer)?\s+join|natural(\s+(left|right)(\s+outer)?)?\s+join)\b</string>
							<key>name</key>
							<string>entity.thread4.log4j</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>thread0</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\[)remediationQueueEndpoint\d\.listener\.0(?=\])</string>
					<key>name</key>
					<string>entity.thread0.log4j</string>
				</dict>
			</array>
		</dict>
		<key>thread1</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\[)remediationQueueEndpoint\d\.listener\.1(?=\])</string>
					<key>name</key>
					<string>entity.thread1.log4j</string>
				</dict>
			</array>
		</dict>
		<key>thread2</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\[)remediationQueueEndpoint\d\.listener\.2(?=\])</string>
					<key>name</key>
					<string>entity.thread2.log4j</string>
				</dict>
			</array>
		</dict>
		<key>thread3</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\[)remediationQueueEndpoint\d\.listener\.3(?=\])</string>
					<key>name</key>
					<string>entity.thread3.log4j</string>
				</dict>
			</array>
		</dict>
		<key>thread4</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\[)remediationQueueEndpoint\d\.listener\.4(?=\])</string>
					<key>name</key>
					<string>entity.thread4.log4j</string>
				</dict>
			</array>
		</dict>
		<key>threads</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#thread0</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#thread1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#thread2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#thread3</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#thread4</string>
				</dict>
			</array>
		</dict>
		<key>timestamp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\d{4}-\d{2}-\d{2}.\d{2}:\d{2}:\d{2},\d{3}</string>
					<key>name</key>
					<string>entity.timestamp.log4j</string>
				</dict>
			</array>
		</dict>
		<key>warn</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^WARN</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>entity.warn.log4j</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#common</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.GCLog4j</string>
	<key>uuid</key>
	<string>59d2eab0-506c-4c33-8e2f-a6a74820383a</string>
</dict>
</plist>
